### ISSUE TITLE
Express version no longer available

### ISSUE THREAD

**Issue by lroal** [blieusong/sybase-ase-docker#2]
Hello, do you happen to have the express version of SAP ASE somewhere ? Only Enteprise and Trial version are available options in the new version of SAP ASE. And the image also get very big on the trial version.
You can direct message me on twitter @lroal or github.
(I am building a new docker image from scratch because I need different charset and default size of db.)

**Comment by blieusong** [comment]
Hi,
I do have it but it's quite big already at around 2Gb. And it's that specific release:
`Adaptive Server Enterprise/16.0 SP03 PL02/EBF 27415` which might not be the latest. Interested?

**Comment by lroal** [comment]
Yes, that would be great.

**Comment by blieusong** [comment]
How could I transfer that big file to you?

**Comment by blieusong** [comment]
https://drive.google.com/file/d/1-3Lc0bnk1yKjvjJdMCU2RcLaozJp6zvx/view?usp=share_link I'll leave it there until you get it.

**Comment by lroal** [comment]
Done downloading.
Thanks.
